spring.datasource.password=chuflitos1

# URL publica del tunel Cloudflare de desarrollo.
# Cambiar solo esta linea cuando reinicies el tunel.
app.base-url=https://appreciated-twins-unlock-corporation.trycloudflare.com

spring.thymeleaf.cache=false

mercadopago.api-url=${MERCADOPAGO_API_URL:https://api.mercadopago.com}
# mercadopago.sandbox=${MERCADOPAGO_SANDBOX:true}
mercadopago.access-token=${MERCADOPAGO_ACCESS_TOKEN:APP_USR-5230299925391190-052912-ba0f4c823f9e99a77be282099fafd071-3272218475}
mercadopago.public-key=${MERCADOPAGO_PUBLIC_KEY:APP_USR-89930658-543b-45b3-8235-c6b4847fea01}
mercadopago.webhook-secret=${MERCADOPAGO_WEBHOOK_SECRET:}

# Credenciales publicas de prueba publicadas por OCA Developers.
oca.api-url=https://integraciones.ocadev.com.ar/epak_tracking_test/Oep_TrackEPak.asmx
oca.usuario=test@oca.com.ar
oca.password=123456
oca.cuit=30-53625919-4
oca.numero-cuenta=111757/001
oca.operativa=94584
oca.operativa-sucursal=78254
