spring.application.name=electrodental
server.port=8080

spring.profiles.default=dev

## Conexión a la DB
spring.datasource.url=jdbc:mysql://localhost:3306/electrodental?createDatabaseIfNotExist=true
spring.datasource.username=root

## COnfiguración extra de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=true

## JPA
## spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
## spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=validate

# True en produccion
# spring.thymeleaf.cache=false
spring.thymeleaf.cache=true

## Folder photos
app.upload.dir=uploads/profiles

## Mercado Pago Checkout Pro
mercadopago.api-url=https://api.mercadopago.com
mercadopago.sandbox=false
# Cuenta de prueba de santi
mercadopago.access-token=APP_USR-5230299925391190-052912-ba0f4c823f9e99a77be282099fafd071-3272218475
mercadopago.public-key=APP_USR-89930658-543b-45b3-8235-c6b4847fea01
mercadopago.webhook-secret=

## OCA e-Pak
oca.api-url=https://integraciones.ocadev.com.ar/epak_tracking_test/Oep_TrackEPak.asmx
oca.usuario=
oca.password=
oca.cuit=
oca.numero-cuenta=
oca.operativa=
oca.operativa-sucursal=
oca.codigo-postal-origen=3500
oca.calle-origen=Roque Saenz Pena
oca.numero-origen=539
oca.localidad-origen=Resistencia
oca.provincia-origen=Chaco
oca.email-origen=info@electrodentalnea.com
oca.contacto-origen=ElectrodentalNea
oca.centro-costo=1
oca.id-franja-horaria=1
oca.id-centro-imposicion-origen=0
oca.confirmar-retiro=true
oca.logistica-inversa=false
