spring.datasource.password=chuflitos1

# URL publica del tunel Cloudflare de desarrollo.
# Cambiar solo esta linea cuando reinicies el tunel.
app.base-url=https://mean-existing-alpha-penguin.trycloudflare.com

spring.thymeleaf.cache=false

# Credenciales publicas de prueba publicadas por OCA Developers.
oca.api-url=https://integraciones.ocadev.com.ar/epak_tracking_test/Oep_TrackEPak.asmx
oca.usuario=test@oca.com.ar
oca.password=123456
oca.cuit=30-53625919-4
oca.numero-cuenta=111757/001
oca.operativa=64665
oca.operativa-sucursal=62342
