spring.datasource.password=Chuflitos100!0

app.base-url=https://electrodentalnea.com.ar

spring.thymeleaf.cache=true

mercadopago.webhook-secret=${MERCADOPAGO_WEBHOOK_SECRET:}

oca.api-url=${OCA_API_URL:https://webservice.oca.com.ar/ePak_tracking/Oep_TrackEPak.asmx}
# Cambiar por las de CLiente
oca.usuario=${OCA_USUARIO:gerencia@electrodentalnea.com.ar}
oca.password=${OCA_PASSWORD:Dent.Tech1}
oca.cuit=${OCA_CUIT:20-28122429-9}
oca.numero-cuenta=${OCA_NUMERO_CUENTA:197795/000}
oca.operativa=${OCA_OPERATIVA:468895}
oca.operativa-sucursal=${OCA_OPERATIVA_SUCURSAL:468896}
oca.operativa-origen-sucursal-domicilio=${OCA_OPERATIVA_SAP:468897}
oca.operativa-origen-sucursal-sucursal=${OCA_OPERATIVA_SAS:468898}
oca.codigo-postal-origen=${OCA_CP_ORIGEN:3500}
oca.calle-origen=${OCA_CALLE_ORIGEN:Roque Saenz Pena}
oca.numero-origen=${OCA_NUMERO_ORIGEN:539}
oca.localidad-origen=${OCA_LOCALIDAD_ORIGEN:Resistencia}
oca.provincia-origen=${OCA_PROVINCIA_ORIGEN:Chaco}
oca.email-origen=${OCA_EMAIL_ORIGEN:soporte@electrodentalnea.com}
oca.contacto-origen=${OCA_CONTACTO_ORIGEN:ElectrodentalNea}
oca.centro-costo=${OCA_CENTRO_COSTO:1}
oca.id-franja-horaria=${OCA_ID_FRANJA_HORARIA:1}
oca.id-centro-imposicion-origen=${OCA_ID_CENTRO_IMPOSICION_ORIGEN:0}
oca.confirmar-retiro=${OCA_CONFIRMAR_RETIRO:true}
oca.logistica-inversa=${OCA_LOGISTICA_INVERSA:false}
